config/routes.rb
Rails.application.routes.draw do

  root 'landing_pages#landing_A'

  get 'landing_pages/landing_B'

  get  'landing_pages/subscribe'

  get 'landing_pages/wireform'

  get 'landing_pages/test'

  get 'landing_pages/educators'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/landing_pages_controller.rb
class LandingPagesController < ApplicationController

  def landing_A

  end

  def landing_B

  end

  def subscribe

  end

  def wireform

  end

  def test

  end

  def educators

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_pages_helper.rb
module LandingPagesHelper
end

app/views/landing_pages/_library_guides.html.erb
<section id="library_guides">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <img src="https://s3-us-west-2.amazonaws.com/innovationlessons/images_landing/Rotated_Innovation_Lessons_001_Landing.png" height="100%" width="100%">
      </div>
      <div class="col-md-4">
        <img src="https://s3-us-west-2.amazonaws.com/innovationlessons/images_landing/Rotated_Innovation_Lessons_002_Landing.png" height="100%" width="100%">
      </div>
      <div class="col-md-4">
       <img src="https://s3-us-west-2.amazonaws.com/innovationlessons/images_landing/Rotated_Innovation_Lessons_003_Landing.png"  alt="innovation_lessons_003" height="100%" width="100%">
      </div>
    </div>
  </div>
</section>

app/views/landing_pages/subscribe.html.erb
<script>
  mixpanel.track("loaded_subscribe_page",{"Page Name": "Landing_Subscribe_Page"});
  mixpanel.track_links("#PayByGumroad", "clicked pagar por tarjeta crédito");
  mixpanel.track_links("#PayByWire", "clicked pagar por transferencia");
</script>

<br><br><br><br>
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <h1>Elige tu medio de pago preferido</h1>
      <h4 style="color:grey">Tarjeta de Crédito o Consignación/Transferencia Bancaria</h4> <br><br><br>
    </div>
    <div class="col-md-2"></div>
  </div>
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">

        <!-- <a href="https://gum.co/innovationlessons">Innovation Lessons Suscripción mensual</a> -->

       <%= link_to"Pagar con tarjeta de crédito", "https://gum.co/innovationlessons", id: "PayByGumroad",class: "btn btn-warning btn-lg btn-block fa fa-credit-card fa-5x", style: "color:white;" %>
        <script type="text/javascript" src="https://gumroad.com/js/gumroad.js"></script>
    </div>

    <div class="col-md-1"></div>
  </div> <br><br>
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">

       <%= link_to"Pagar por consignación o transferencia bancaria", landing_pages_wireform_path, id: "PayByWire", class: "btn btn-default btn-lg btn-block fa fa-usd fa-5x", style: "color:grey;" %>
    </div>
    <div class="col-md-1"></div>
  </div>
</div>

app/views/landing_pages/test.html.erb
<!-- <br><br><br><br><br><br>
<script type="text/javascript" src="https://gumroad.com/js/gumroad.js"></script>
<a class="gumroad-button" href="https://gumroad.com/l/demo" style="background-color:orange; color: black">GET MY WEEKLY GUIDE</a> -->

app/views/landing_pages/wireform.html.erb
<script>
  mixpanel.track("Wire_Form_loaded",{"Page Name": "Wire_Form_loaded"});
</script>


<br><br><br><br>
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <h1>Aún no tenemos esta opción de pago habilitada. Déjanos tus datos y te informaremos cuando esté lista o  <span > <a href="#" style="color:orange;">paga con tarjeta de crédito aquí</a></span></h1>
       <br><br><br>
    </div>
    <div class="col-md-2"></div>
  </div>

  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
       <!-- Begin MailChimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/classic-081711.css" rel="stylesheet" type="text/css">
<style type="text/css">
  #mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
  /* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
     We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="//innovationlessons.us10.list-manage.com/subscribe/post?u=d24dc668a2756e8723eb455cf&amp;id=a9ce153626" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
  <h2>Suscríbete a la lista de interesados en pago por transferencia bancaria</h2>
<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
<div class="mc-field-group">
  <label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
</label>
  <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
<div class="mc-field-group">
  <label for="mce-FNAME">First Name </label>
  <input type="text" value="" name="FNAME" class="" id="mce-FNAME">
</div>
<div class="mc-field-group">
  <label for="mce-LNAME">¿Cuál es la principal razón por la que estás interesado en Innovation Lessons? </label>
  <input type="text" value="" name="LNAME" class="" id="mce-LNAME">
</div>
  <div id="mce-responses" class="clear">
    <div class="response" id="mce-error-response" style="display:none"></div>
    <div class="response" id="mce-success-response" style="display:none"></div>
  </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;"><input type="text" name="b_d24dc668a2756e8723eb455cf_a9ce153626" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Suscribirme" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text'; /*
 * Translated default messages for the $ validation plugin.
 * Locale: ES
 */
$.extend($.validator.messages, {
  required: "Este campo es obligatorio.",
  remote: "Por favor, rellena este campo.",
  email: "Por favor, escribe una dirección de correo válida",
  url: "Por favor, escribe una URL válida.",
  date: "Por favor, escribe una fecha válida.",
  dateISO: "Por favor, escribe una fecha (ISO) válida.",
  number: "Por favor, escribe un número entero válido.",
  digits: "Por favor, escribe sólo dígitos.",
  creditcard: "Por favor, escribe un número de tarjeta válido.",
  equalTo: "Por favor, escribe el mismo valor de nuevo.",
  accept: "Por favor, escribe un valor con una extensión aceptada.",
  maxlength: $.validator.format("Por favor, no escribas más de {0} caracteres."),
  minlength: $.validator.format("Por favor, no escribas menos de {0} caracteres."),
  rangelength: $.validator.format("Por favor, escribe un valor entre {0} y {1} caracteres."),
  range: $.validator.format("Por favor, escribe un valor entre {0} y {1}."),
  max: $.validator.format("Por favor, escribe un valor menor o igual a {0}."),
  min: $.validator.format("Por favor, escribe un valor mayor o igual a {0}.")
});}(jQuery));var $mcj = jQuery.noConflict(true);</script>
<!--End mc_embed_signup-->
</div>

  </div>
  <div class="col-md-2"></div>
</div>

app/views/layouts/_landing_nav.html.erb
    <nav class="navbar navbar-fixed-top col-md-12" style="background-color: black" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar" style="background-color:yellow">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <%=link_to "Innovation Lessons",root_path , class: "navbar-brand", style: "color:yellow" %>
        </div> <!-- nav-header -->

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
          <%= link_to"Suscribirme $10.99", landing_pages_subscribe_path, id: "suscribirmeLanding", class: "btn", style: "color:white; background-color:orange;margin-top:10px" %>
          </ul>

        </div> <!-- #id=navbar -->
      </div><!-- container-fluid -->
    </nav><!-- nav -->

<!-- <div >
          <div class="input-group" style="margin-top: 9px">
            <input type="text" class="form-control" placeholder="de que quieres aprender hoy...">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">buscar!</button>
            </span>
          </div>/input-group -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InnovationLessons</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<!-- start Mixpanel --><script type="text/javascript">(function(f,b){if(!b.__SV){var a,e,i,g;window.mixpanel=b;b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.track_charge people.clear_charges people.delete_user".split(" ");
for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2;a=f.createElement("script");a.type="text/javascript";a.async=!0;a.src="//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";e=f.getElementsByTagName("script")[0];e.parentNode.insertBefore(a,e)}})(document,window.mixpanel||[]);
mixpanel.init("88dd0007364587bef98e567de6af6a12");</script><!-- end Mixpanel -->
</head>
<%= render 'layouts/landing_nav' %>
<body>

<%= yield %>
<!-- begin olark code -->
<script data-cfasync="false" type='text/javascript'>/*<![CDATA[*/window.olark||(function(c){var f=window,d=document,l=f.location.protocol=="https:"?"https:":"http:",z=c.name,r="load";var nt=function(){
f[z]=function(){
(a.s=a.s||[]).push(arguments)};var a=f[z]._={
},q=c.methods.length;while(q--){(function(n){f[z][n]=function(){
f[z]("call",n,arguments)}})(c.methods[q])}a.l=c.loader;a.i=nt;a.p={
0:+new Date};a.P=function(u){
a.p[u]=new Date-a.p[0]};function s(){
a.P(r);f[z](r)}f.addEventListener?f.addEventListener(r,s,false):f.attachEvent("on"+r,s);var ld=function(){function p(hd){
hd="head";return["<",hd,"></",hd,"><",i,' onl' + 'oad="var d=',g,";d.getElementsByTagName('head')[0].",j,"(d.",h,"('script')).",k,"='",l,"//",a.l,"'",'"',"></",i,">"].join("")}var i="body",m=d[i];if(!m){
return setTimeout(ld,100)}a.P(1);var j="appendChild",h="createElement",k="src",n=d[h]("div"),v=n[j](d[h](z)),b=d[h]("iframe"),g="document",e="domain",o;n.style.display="none";m.insertBefore(n,m.firstChild).id=z;b.frameBorder="0";b.id=z+"-loader";if(/MSIE[ ]+6/.test(navigator.userAgent)){
b.src="javascript:false"}b.allowTransparency="true";v[j](b);try{
b.contentWindow[g].open()}catch(w){
c[e]=d[e];o="javascript:var d="+g+".open();d.domain='"+d.domain+"';";b[k]=o+"void(0);"}try{
var t=b.contentWindow[g];t.write(p());t.close()}catch(x){
b[k]=o+'d.write("'+p().replace(/"/g,String.fromCharCode(92)+'"')+'");d.close();'}a.P(2)};ld()};nt()})({
loader: "static.olark.com/jsclient/loader0.js",name:"olark",methods:["configure","extend","declare","identify"]});
/* custom configuration goes here (www.olark.com/documentation) */
olark.identify('8894-446-10-5338');/*]]>*/</script><noscript><a href="https://www.olark.com/site/8894-446-10-5338/contact" title="Contact us" target="_blank">Questions? Feedback?</a> powered by <a href="http://www.olark.com?welcome" title="Olark live chat software">Olark live chat software</a></noscript>
<!-- end olark code -->
</body>
</html>